/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;

/**
 *
 * @author espin
 */
public class Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Cuenta
     */
    public Cuenta() {
        initComponents();
    }
    
    CuentasAlmacenadas cuentas = new CuentasAlmacenadas();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        imgCuenta = new javax.swing.JLabel();
        aposTitle = new javax.swing.JLabel();
        iniciarSesionTitle = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contraseña = new javax.swing.JLabel();
        fieldContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        buttonIngreso = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        errorInSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(600, 280));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 84, 189)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgCuenta.jpg"))); // NOI18N
        jPanel2.add(imgCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        aposTitle.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        aposTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/florInicio.png"))); // NOI18N
        aposTitle.setText("APOS");
        jPanel2.add(aposTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, 50));

        iniciarSesionTitle.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        iniciarSesionTitle.setText("INICIAR SESION");
        jPanel2.add(iniciarSesionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        usuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        usuario.setText("USUARIO");
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, -1));

        fieldUsuario.setForeground(new java.awt.Color(204, 204, 204));
        fieldUsuario.setText("Ingrese su nombre de usuario");
        fieldUsuario.setBorder(null);
        fieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldUsuarioMousePressed(evt);
            }
        });
        fieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(fieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 370, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 370, -1));

        contraseña.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        contraseña.setText("CONTRASEÑA");
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        fieldContraseña.setForeground(new java.awt.Color(204, 204, 204));
        fieldContraseña.setText("++++++++++");
        fieldContraseña.setBorder(null);
        fieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldContraseñaMousePressed(evt);
            }
        });
        fieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(fieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 370, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 370, 20));

        buttonIngreso.setBackground(new java.awt.Color(29, 84, 189));
        buttonIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonIngresoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonIngresoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonIngresoMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INGRESAR");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout buttonIngresoLayout = new javax.swing.GroupLayout(buttonIngreso);
        buttonIngreso.setLayout(buttonIngresoLayout);
        buttonIngresoLayout.setHorizontalGroup(
            buttonIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonIngresoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        buttonIngresoLayout.setVerticalGroup(
            buttonIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonIngresoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(buttonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 170, 50));

        errorInSesion.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        errorInSesion.setForeground(new java.awt.Color(255, 255, 255));
        errorInSesion.setText("*Contraseña o nombre de usuario incorrectos. Intente nuevamente");
        jPanel2.add(errorInSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsuarioActionPerformed

    private void buttonIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIngresoMouseClicked
        // TODO add your handling code here:
        buttonIngreso.setBackground(new Color(20,75,180));
    }//GEN-LAST:event_buttonIngresoMouseClicked

    private void buttonIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIngresoMouseExited
        // TODO add your handling code here:
        buttonIngreso.setBackground(new Color(29,84,189));
    }//GEN-LAST:event_buttonIngresoMouseExited

    private void fieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContraseñaActionPerformed

    private void fieldUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldUsuarioMousePressed
        // TODO add your handling code here:
        errorInSesion.setForeground(Color.white);
        if(fieldUsuario.getText().equals("Ingrese su nombre de usuario")){
            fieldUsuario.setText("");
            fieldUsuario.setForeground(Color.black);
        }
        if(String.valueOf(fieldContraseña.getPassword()).isEmpty()){
            fieldContraseña.setText("++++++++++");
        fieldContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_fieldUsuarioMousePressed

    private void fieldContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldContraseñaMousePressed
        // TODO add your handling code here:
        errorInSesion.setForeground(Color.white);
        if(String.valueOf(fieldContraseña.getPassword()).equals("++++++++++")){
            fieldContraseña.setText("");
            fieldContraseña.setForeground(Color.black);
        }
        if(fieldUsuario.getText().isEmpty()){
            fieldUsuario.setText("Ingrese su nombre de usuario");
            fieldUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_fieldContraseñaMousePressed

    private void buttonIngresoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonIngresoMousePressed
        // TODO add your handling code here:
        buttonIngreso.setBackground(new Color(20,75,180));
        String contraseña = String.valueOf(fieldContraseña.getPassword());
        String user = fieldUsuario.getText();
        boolean valid = cuentas.validar(user, contraseña);
        if(valid){
            this.dispose();
            Principal.tipoUsuario.setText(cuentas.privilegioUser(user));
            Primera prim = new Primera();
            Principal.ShowPanel(prim);
            Principal.Datos(user,contraseña);
        }
        else{
            errorInSesion.setForeground(Color.red);
        }
    }//GEN-LAST:event_buttonIngresoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aposTitle;
    private javax.swing.JPanel buttonIngreso;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel errorInSesion;
    private javax.swing.JPasswordField fieldContraseña;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel imgCuenta;
    private javax.swing.JLabel iniciarSesionTitle;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
