package ventanas;

import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author espin
 */
public class Facturacion extends javax.swing.JPanel {

    /**
     * Creates new form Facturacion
     */
    Arreglo Facturacion;
    Inventory inventario;
    DefaultTableModel model;
    
    public Facturacion(Inventory inventario, Arreglo Factura) {
        this.inventario = inventario;
        this.Facturacion = Factura;
        initComponents();
        actualizaTabla();
    }
    DefaultTableCellRenderer alinear;
    private final String[] columNames = {"Id Factura","Referencia producto","Cantidad de articulos", "Precio total","Fecha"};
    private Object [][] datosFilas;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void actualizaTabla(){
        this.facturacionTabla.repaint(30, 380, 1720, 517);
        model = new DefaultTableModel(datosFilas,columNames){
            @Override
            public boolean isCellEditable(int row, int column) 
            {
                return false; 
            }
        };
        ((DefaultTableCellRenderer)this.facturacionTabla.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        alinear = new DefaultTableCellRenderer();
        alinear.setHorizontalAlignment(SwingConstants.CENTER);
        alinear.setBackground(Color.WHITE);
        this.facturacionTabla.setModel(model);
        this.facturacionTabla.setBounds(30, 380, 1720, 517);
        for(int i=0;i<=4;i++){
            this.facturacionTabla.getColumnModel().getColumn(i).setCellRenderer(alinear);
        }
        this.facturacionTabla.setShowGrid(true);
        this.facturacionTabla.setGridColor(new Color(242,242,242));
        Facturacion.printFacturas(model);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        barraGrisSup = new javax.swing.JPanel();
        Ayuda = new javax.swing.JLabel();
        Ventana = new javax.swing.JLabel();
        Vista = new javax.swing.JLabel();
        Reportes = new javax.swing.JLabel();
        Consultas = new javax.swing.JLabel();
        Datos = new javax.swing.JLabel();
        Edicion = new javax.swing.JLabel();
        Archivo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Facturación = new javax.swing.JLabel();
        InventarioOpc = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Pedidos = new javax.swing.JLabel();
        Finanzas = new javax.swing.JLabel();
        BarrAñadir = new javax.swing.JLabel();
        BarrEliminar = new javax.swing.JLabel();
        barraInventario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        facturacionTabla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1777, 997));
        setMinimumSize(new java.awt.Dimension(1777, 997));
        setPreferredSize(new java.awt.Dimension(1777, 997));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraGrisSup.setBackground(new java.awt.Color(179, 179, 179));
        barraGrisSup.setMaximumSize(new java.awt.Dimension(1777, 38));
        barraGrisSup.setMinimumSize(new java.awt.Dimension(1777, 38));
        barraGrisSup.setName(""); // NOI18N
        barraGrisSup.setPreferredSize(new java.awt.Dimension(1777, 38));
        barraGrisSup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ayuda.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Ayuda.setForeground(new java.awt.Color(255, 255, 255));
        Ayuda.setText("Ayuda");
        Ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 8, -1, -1));

        Ventana.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Ventana.setForeground(new java.awt.Color(255, 255, 255));
        Ventana.setText("Ventana");
        Ventana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 8, -1, -1));

        Vista.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Vista.setForeground(new java.awt.Color(255, 255, 255));
        Vista.setText("Vista");
        Vista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 8, -1, -1));

        Reportes.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Reportes.setForeground(new java.awt.Color(255, 255, 255));
        Reportes.setText("Reportes");
        Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 8, -1, -1));

        Consultas.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Consultas.setForeground(new java.awt.Color(255, 255, 255));
        Consultas.setText("Consultas");
        Consultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 8, -1, -1));

        Datos.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setText("Datos");
        Datos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 8, -1, -1));

        Edicion.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Edicion.setForeground(new java.awt.Color(255, 255, 255));
        Edicion.setText("Edición");
        Edicion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 8, -1, -1));

        Archivo.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Archivo.setForeground(new java.awt.Color(255, 255, 255));
        Archivo.setText("Archivo");
        Archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, -1, -1));

        add(barraGrisSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(1736, 137));
        jPanel2.setMinimumSize(new java.awt.Dimension(1736, 137));
        jPanel2.setPreferredSize(new java.awt.Dimension(1736, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Facturación.setBackground(new java.awt.Color(241, 241, 241));
        Facturación.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Facturación.setForeground(new java.awt.Color(102, 102, 102));
        Facturación.setText("Facturación");
        Facturación.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Facturación.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Facturación.setMaximumSize(new java.awt.Dimension(1736, 49));
        Facturación.setMinimumSize(new java.awt.Dimension(1736, 49));
        Facturación.setOpaque(true);
        Facturación.setPreferredSize(new java.awt.Dimension(1736, 49));
        jPanel2.add(Facturación, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 140, -1));

        InventarioOpc.setBackground(new java.awt.Color(241, 241, 241));
        InventarioOpc.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        InventarioOpc.setForeground(new java.awt.Color(102, 102, 102));
        InventarioOpc.setText("Inventario");
        InventarioOpc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InventarioOpc.setMaximumSize(new java.awt.Dimension(1736, 49));
        InventarioOpc.setMinimumSize(new java.awt.Dimension(1736, 49));
        InventarioOpc.setPreferredSize(new java.awt.Dimension(1736, 49));
        InventarioOpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventarioOpcMouseClicked(evt);
            }
        });
        jPanel2.add(InventarioOpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 120, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 49, 1230, 10));

        Pedidos.setBackground(new java.awt.Color(29, 84, 189));
        Pedidos.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Pedidos.setForeground(new java.awt.Color(102, 102, 102));
        Pedidos.setText("Pedidos");
        Pedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pedidos.setMaximumSize(new java.awt.Dimension(1736, 49));
        Pedidos.setMinimumSize(new java.awt.Dimension(1736, 49));
        Pedidos.setPreferredSize(new java.awt.Dimension(1736, 49));
        Pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidosMouseClicked(evt);
            }
        });
        jPanel2.add(Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 100, -1));

        Finanzas.setBackground(new java.awt.Color(29, 84, 189));
        Finanzas.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Finanzas.setForeground(new java.awt.Color(102, 102, 102));
        Finanzas.setText("Finanzas");
        Finanzas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Finanzas.setMaximumSize(new java.awt.Dimension(1736, 49));
        Finanzas.setMinimumSize(new java.awt.Dimension(1736, 49));
        Finanzas.setPreferredSize(new java.awt.Dimension(1736, 49));
        Finanzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinanzasMouseClicked(evt);
            }
        });
        jPanel2.add(Finanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 110, -1));

        BarrAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barraAñadir.png"))); // NOI18N
        BarrAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarrAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarrAñadirMouseClicked(evt);
            }
        });
        jPanel2.add(BarrAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        BarrEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barraEliminar.png"))); // NOI18N
        BarrEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarrEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarrEliminarMouseClicked(evt);
            }
        });
        jPanel2.add(BarrEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 50, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 53, 1736, 137));

        barraInventario.setBackground(new java.awt.Color(29, 84, 189));
        barraInventario.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        barraInventario.setForeground(new java.awt.Color(255, 255, 255));
        barraInventario.setText("                       Facturación");
        barraInventario.setMaximumSize(new java.awt.Dimension(1736, 49));
        barraInventario.setMinimumSize(new java.awt.Dimension(1736, 49));
        barraInventario.setOpaque(true);
        barraInventario.setPreferredSize(new java.awt.Dimension(1736, 49));
        add(barraInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 209, -1, -1));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1720, 517));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1720, 517));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1720, 517));

        facturacionTabla.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        facturacionTabla.setForeground(new java.awt.Color(51, 51, 51));
        facturacionTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Factura", "Referencia producto", "Cantidad de articulos", "Precio total", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        facturacionTabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        facturacionTabla.setMaximumSize(new java.awt.Dimension(1720, 517));
        facturacionTabla.setMinimumSize(new java.awt.Dimension(1720, 517));
        facturacionTabla.setPreferredSize(new java.awt.Dimension(1720, 517));
        jScrollPane1.setViewportView(facturacionTabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 1720, 520));

        jPanel5.setBackground(new java.awt.Color(29, 84, 189));
        jPanel5.setMaximumSize(new java.awt.Dimension(1736, 45));
        jPanel5.setMinimumSize(new java.awt.Dimension(1736, 45));
        jPanel5.setPreferredSize(new java.awt.Dimension(1736, 45));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabla de Facturas");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 331, -1, -1));
    }// </editor-fold>                        

    private void InventarioOpcMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        Inventario ventInv = new Inventario(inventario,Facturacion);
        Principal.ShowPanel(ventInv);
    }                                          

    private void PedidosMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        Pedidos ventPed = new Pedidos(inventario,Facturacion);
        Principal.ShowPanel(ventPed);
    }                                    

    private void FinanzasMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        Finanzas ventFin = new Finanzas(inventario,Facturacion);
        Principal.ShowPanel(ventFin);
    }                                     

    private void BarrAñadirMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        Factura factura;
        factura = new Factura(
                Integer.parseInt(JOptionPane.showInputDialog("Inserte el id de la factura")),
                Integer.parseInt(JOptionPane.showInputDialog("Inserte el id del producto")),
                Integer.parseInt(JOptionPane.showInputDialog("Inserte la cantidad")),
                Integer.parseInt(JOptionPane.showInputDialog("Inserte el valor total")),
                new Date());
        Facturacion.insert(factura);
        actualizaTabla();
    }                                       

    private void BarrEliminarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        this.Facturacion.delete(
            Integer.parseInt(JOptionPane.showInputDialog("Inserte la id(o referencia) del producto a eliminar")));
        actualizaTabla();
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Archivo;
    private javax.swing.JLabel Ayuda;
    private javax.swing.JLabel BarrAñadir;
    private javax.swing.JLabel BarrEliminar;
    private javax.swing.JLabel Consultas;
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel Edicion;
    private javax.swing.JLabel Facturación;
    private javax.swing.JLabel Finanzas;
    private javax.swing.JLabel InventarioOpc;
    private javax.swing.JLabel Pedidos;
    private javax.swing.JLabel Reportes;
    private javax.swing.JLabel Ventana;
    private javax.swing.JLabel Vista;
    private javax.swing.JPanel barraGrisSup;
    private javax.swing.JLabel barraInventario;
    public javax.swing.JTable facturacionTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration                   
}