package ventanas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author espin
 */
public class Inventario extends javax.swing.JPanel {

    /**
     * Creates new form Inventario
     */
    Inventory inventario;
    Arreglo Facturacion;
    DefaultTableModel model;
    Serialize<Inventory> sz = new Serialize<>();

    public Inventario() {
    }
    DefaultTableCellRenderer alinear;
    private final String[] columNames = {"Id","Nombre","Precio Distribuidor", "Precio Venta","Cantidad"};
    private Object [][] datosFilas;
    Calculadora calculadora = new Calculadora();
    
    public Inventario(Inventory inventario,Arreglo Facturacion) {
        this.inventario = inventario;
        this.Facturacion = Facturacion;
        initComponents();
        actualizaTabla();
        PanelCalculadora.removeAll();
        PanelCalculadora.add(calculadora,BorderLayout.CENTER);
        PanelCalculadora.revalidate();
        PanelCalculadora.repaint(); 
    }
    public void actualizaTabla(){
        this.inventarioTabla.repaint(676, 375, 1060, 520);
        model = new DefaultTableModel(datosFilas,columNames){
            @Override
            public boolean isCellEditable(int row, int column) 
            {
                return false; 
            }
        };
        ((DefaultTableCellRenderer)this.inventarioTabla.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        alinear = new DefaultTableCellRenderer();
        alinear.setHorizontalAlignment(SwingConstants.CENTER);
        alinear.setBackground(Color.WHITE);
        this.inventarioTabla.setModel(model);
        this.inventarioTabla.setBounds(676, 375, 1060, 520);
        for(int i=0;i<=4;i++){
            this.inventarioTabla.getColumnModel().getColumn(i).setCellRenderer(alinear);
        }
        this.inventarioTabla.setShowGrid(true);
        this.inventarioTabla.setGridColor(new Color(242,242,242));
        this.inventario.print(this.inventario.root,this.model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        barraInventario = new javax.swing.JLabel();
        barraGrisSup = new javax.swing.JPanel();
        Ayuda = new javax.swing.JLabel();
        Ventana = new javax.swing.JLabel();
        Vista = new javax.swing.JLabel();
        Reportes = new javax.swing.JLabel();
        Consultas = new javax.swing.JLabel();
        Datos = new javax.swing.JLabel();
        Edicion = new javax.swing.JLabel();
        Archivo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Nuevo = new javax.swing.JLabel();
        Modificar = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textoBusqueda = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Finanzas = new javax.swing.JLabel();
        Pedidos = new javax.swing.JLabel();
        Facturación = new javax.swing.JLabel();
        InventarioOpc = new javax.swing.JLabel();
        BarrCambId = new javax.swing.JLabel();
        BarrEliminar = new javax.swing.JLabel();
        BarrAñadir = new javax.swing.JLabel();
        BarrBuscar = new javax.swing.JLabel();
        BarrGuardar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PanelCalculadora = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventarioTabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1777, 997));
        setMinimumSize(new java.awt.Dimension(1777, 997));
        setPreferredSize(new java.awt.Dimension(1777, 997));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraInventario.setBackground(new java.awt.Color(29, 84, 189));
        barraInventario.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        barraInventario.setForeground(new java.awt.Color(255, 255, 255));
        barraInventario.setText("                       Inventario");
        barraInventario.setMaximumSize(new java.awt.Dimension(1736, 49));
        barraInventario.setMinimumSize(new java.awt.Dimension(1736, 49));
        barraInventario.setOpaque(true);
        barraInventario.setPreferredSize(new java.awt.Dimension(1736, 49));
        add(barraInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 209, -1, -1));

        barraGrisSup.setBackground(new java.awt.Color(179, 179, 179));
        barraGrisSup.setMaximumSize(new java.awt.Dimension(1777, 38));
        barraGrisSup.setMinimumSize(new java.awt.Dimension(1777, 38));
        barraGrisSup.setName(""); // NOI18N
        barraGrisSup.setPreferredSize(new java.awt.Dimension(1777, 38));
        barraGrisSup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ayuda.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Ayuda.setForeground(new java.awt.Color(255, 255, 255));
        Ayuda.setText("Ayuda");
        Ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 8, -1, -1));

        Ventana.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Ventana.setForeground(new java.awt.Color(255, 255, 255));
        Ventana.setText("Ventana");
        Ventana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 8, -1, -1));

        Vista.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Vista.setForeground(new java.awt.Color(255, 255, 255));
        Vista.setText("Vista");
        Vista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 8, -1, -1));

        Reportes.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Reportes.setForeground(new java.awt.Color(255, 255, 255));
        Reportes.setText("Reportes");
        Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 8, -1, -1));

        Consultas.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Consultas.setForeground(new java.awt.Color(255, 255, 255));
        Consultas.setText("Consultas");
        Consultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 8, -1, -1));

        Datos.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Datos.setForeground(new java.awt.Color(255, 255, 255));
        Datos.setText("Datos");
        Datos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 8, -1, -1));

        Edicion.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Edicion.setForeground(new java.awt.Color(255, 255, 255));
        Edicion.setText("Edición");
        Edicion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 8, -1, -1));

        Archivo.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Archivo.setForeground(new java.awt.Color(255, 255, 255));
        Archivo.setText("Archivo");
        Archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barraGrisSup.add(Archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 8, -1, -1));

        add(barraGrisSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(223, 223, 223));
        jPanel3.setMaximumSize(new java.awt.Dimension(1736, 49));
        jPanel3.setMinimumSize(new java.awt.Dimension(1736, 49));
        jPanel3.setPreferredSize(new java.awt.Dimension(1736, 49));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nuevo.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Nuevo.setForeground(new java.awt.Color(51, 51, 51));
        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadirObjeto.png"))); // NOI18N
        Nuevo.setText("Añadir");
        Nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevoMouseClicked(evt);
            }
        });
        jPanel3.add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 10, -1, -1));

        Modificar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Modificar.setForeground(new java.awt.Color(51, 51, 51));
        Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        Modificar.setText("Modificar");
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
        });
        jPanel3.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 10, -1, -1));

        Eliminar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(51, 51, 51));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });
        jPanel3.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(939, 32));
        jPanel1.setMinimumSize(new java.awt.Dimension(939, 32));
        jPanel1.setPreferredSize(new java.awt.Dimension(939, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        Buscar.setForeground(new java.awt.Color(51, 51, 51));
        Buscar.setText("Buscar");
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 2, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 8, 10, 20));

        textoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        textoBusqueda.setText("Ingrese el nombre exacto del producto que desea buscar");
        textoBusqueda.setBorder(null);
        textoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textoBusquedaMouseClicked(evt);
            }
        });
        textoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoBusquedaKeyPressed(evt);
            }
        });
        jPanel1.add(textoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 9, 780, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 9, 930, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 257, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(1736, 137));
        jPanel2.setMinimumSize(new java.awt.Dimension(1736, 137));
        jPanel2.setPreferredSize(new java.awt.Dimension(1736, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Finanzas.setBackground(new java.awt.Color(29, 84, 189));
        Finanzas.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Finanzas.setForeground(new java.awt.Color(102, 102, 102));
        Finanzas.setText("Finanzas");
        Finanzas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Finanzas.setMaximumSize(new java.awt.Dimension(1736, 49));
        Finanzas.setMinimumSize(new java.awt.Dimension(1736, 49));
        Finanzas.setPreferredSize(new java.awt.Dimension(1736, 49));
        Finanzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinanzasMouseClicked(evt);
            }
        });
        jPanel2.add(Finanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 110, -1));

        Pedidos.setBackground(new java.awt.Color(29, 84, 189));
        Pedidos.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Pedidos.setForeground(new java.awt.Color(102, 102, 102));
        Pedidos.setText("Pedidos");
        Pedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pedidos.setMaximumSize(new java.awt.Dimension(1736, 49));
        Pedidos.setMinimumSize(new java.awt.Dimension(1736, 49));
        Pedidos.setPreferredSize(new java.awt.Dimension(1736, 49));
        Pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PedidosMouseClicked(evt);
            }
        });
        jPanel2.add(Pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 100, -1));

        Facturación.setBackground(new java.awt.Color(29, 84, 189));
        Facturación.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        Facturación.setForeground(new java.awt.Color(102, 102, 102));
        Facturación.setText("Facturación");
        Facturación.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Facturación.setMaximumSize(new java.awt.Dimension(1736, 49));
        Facturación.setMinimumSize(new java.awt.Dimension(1736, 49));
        Facturación.setPreferredSize(new java.awt.Dimension(1736, 49));
        Facturación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturaciónMouseClicked(evt);
            }
        });
        jPanel2.add(Facturación, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 140, -1));

        InventarioOpc.setBackground(new java.awt.Color(241, 241, 241));
        InventarioOpc.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        InventarioOpc.setForeground(new java.awt.Color(102, 102, 102));
        InventarioOpc.setText("Inventario");
        InventarioOpc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        InventarioOpc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InventarioOpc.setMaximumSize(new java.awt.Dimension(1736, 49));
        InventarioOpc.setMinimumSize(new java.awt.Dimension(1736, 49));
        InventarioOpc.setOpaque(true);
        InventarioOpc.setPreferredSize(new java.awt.Dimension(1736, 49));
        jPanel2.add(InventarioOpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 120, -1));

        BarrCambId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barraCambiarID.png"))); // NOI18N
        BarrCambId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarrCambId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarrCambIdMouseClicked(evt);
            }
        });
        jPanel2.add(BarrCambId, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 50, -1, -1));

        BarrEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barraEliminar.png"))); // NOI18N
        BarrEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarrEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarrEliminarMouseClicked(evt);
            }
        });
        jPanel2.add(BarrEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 50, -1, -1));

        BarrAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barraAñadir.png"))); // NOI18N
        BarrAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarrAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarrAñadirMouseClicked(evt);
            }
        });
        jPanel2.add(BarrAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 50, -1, -1));

        BarrBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barraBuscar.png"))); // NOI18N
        BarrBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarrBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarrBuscarMouseClicked(evt);
            }
        });
        jPanel2.add(BarrBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 50, -1, -1));

        BarrGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/barraGuardar.png"))); // NOI18N
        BarrGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BarrGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarrGuardarMouseClicked(evt);
            }
        });
        jPanel2.add(BarrGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 49, 1230, 10));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 53, 1736, 137));

        PanelCalculadora.setBackground(new java.awt.Color(255, 255, 255));
        PanelCalculadora.setMaximumSize(new java.awt.Dimension(615, 567));
        PanelCalculadora.setMinimumSize(new java.awt.Dimension(615, 567));
        PanelCalculadora.setPreferredSize(new java.awt.Dimension(615, 567));
        add(PanelCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 331, -1, -1));

        jPanel5.setBackground(new java.awt.Color(29, 84, 189));
        jPanel5.setMaximumSize(new java.awt.Dimension(1060, 45));
        jPanel5.setMinimumSize(new java.awt.Dimension(1060, 45));
        jPanel5.setPreferredSize(new java.awt.Dimension(1060, 45));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabla de inventario");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, -1, -1));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 331, -1, -1));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1060, 517));

        inventarioTabla.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inventarioTabla.setForeground(new java.awt.Color(51, 51, 51));
        inventarioTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Precio Distribuidor", "Precio Venta", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventarioTabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        inventarioTabla.setMaximumSize(new java.awt.Dimension(1060, 200000));
        inventarioTabla.setMinimumSize(new java.awt.Dimension(1060, 517));
        inventarioTabla.setPreferredSize(new java.awt.Dimension(1060, 517));
        jScrollPane1.setViewportView(inventarioTabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 375, 1060, 520));
    }// </editor-fold>                        

    private void NuevoMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        this.inventario.Insertar(JOptionPane.showInputDialog("Inserte el nombre del producto"),
                            Integer.parseInt(JOptionPane.showInputDialog("Inserte la id(o referencia) del producto")),
                            Integer.parseInt(JOptionPane.showInputDialog("Inserte el precio de Distribuidor del producto")),
                            Integer.parseInt(JOptionPane.showInputDialog("Inserte el precio de Venta del producto")),
                            Integer.parseInt(JOptionPane.showInputDialog("Inserte la cantidad disponile")));
        actualizaTabla();
    }                                  

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        this.inventario.Eliminar(
        Integer.parseInt(JOptionPane.showInputDialog("Inserte la id(o referencia) del producto a eliminar")));
        actualizaTabla();
    }                                     

    private void BarrAñadirMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        this.inventario.Insertar(JOptionPane.showInputDialog("Inserte el nombre del producto"),
                            Integer.parseInt(JOptionPane.showInputDialog("Inserte la id(o referencia) del producto")),
                            Integer.parseInt(JOptionPane.showInputDialog("Inserte el precio de Distribuidor del producto")),
                            Integer.parseInt(JOptionPane.showInputDialog("Inserte el precio de Venta del producto")),
                            Integer.parseInt(JOptionPane.showInputDialog("Inserte la cantidad disponile")));
        actualizaTabla();
    }                                       

    private void BarrEliminarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        this.inventario.Eliminar(
        Integer.parseInt(JOptionPane.showInputDialog("Inserte la id(o referencia) del producto a eliminar")));
        actualizaTabla();
    }                                         

    private void BarrCambIdMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        int ref = Integer.parseInt(JOptionPane.showInputDialog("Inserte la id(o referencia) actual del producto"));
        Objeto refOb = inventario.search(ref);
        int newRef = Integer.parseInt(JOptionPane.showInputDialog("Inserte la nueva id(o referencia) del producto"));
        this.inventario.Eliminar(ref);
        this.inventario.Insertar(refOb.getNombre(),newRef,refOb.getPrecio_distribuidor(),refOb.getPrecio_venta(),refOb.getCantidad());
        actualizaTabla();
    }                                       

    private void textoBusquedaKeyPressed(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
            Objeto obj = inventario.searchByName(textoBusqueda.getText());
            if(obj!=null){
                JOptionPane.showMessageDialog(null,"Se ha encontradoo el articulo"
                                    + "\nNombre: " + obj.getNombre()
                                    + "\nId: " + obj.getId()
                                    + "\nPrecio Distribuidor: " + obj.getPrecio_distribuidor()
                                    + "\nPrecio Venta: " + obj.getPrecio_venta()
                                    + "\nCantidad de unidades: " + obj.getCantidad()
                );
            }
            else{
                JOptionPane.showMessageDialog(null,"Articulo no encontrado, intente nuevamente");
            }
            textoBusqueda.setForeground(new Color(153,153,153));
            textoBusqueda.setText("Ingrese el nombre exacto del producto que desea buscar");
        }
    }                                        

    private void textoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        textoBusqueda.setText("");
        textoBusqueda.setForeground(Color.black);
    }                                          

    private void BarrBuscarMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        
        Objeto obj = inventario.search(
                Integer.parseInt(JOptionPane.showInputDialog("Inserte la id(o referencia) del producto que desea buscar"))
        );
        if(obj!=null){
            JOptionPane.showMessageDialog(null,"Se ha encontradoo el articulo"
                                    + "\nNombre: " + obj.getNombre()
                                    + "\nId: " + obj.getId()
                                    + "\nPrecio Distribuidor: " + obj.getPrecio_distribuidor()
                                    + "\nPrecio Venta: " + obj.getPrecio_venta()
                                    + "\nCantidad de unidades: " + obj.getCantidad()
                );
        }
        else{
            JOptionPane.showMessageDialog(null,"Articulo no encontrado, intente nuevamente");
        }
    }                                       

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        Objeto obj = inventario.search(
                Integer.parseInt(JOptionPane.showInputDialog("Inserte la id(o referencia) del producto que desea modificar"))
        );
        String[] opciones = {"Selecciona","Nombre del producto","Cantidad","Precio Venta","Precio Distribuidor"}; 
        String modif = (String)JOptionPane.showInputDialog(null, "Selecciona el valor que quieres modificar", 
                "Modificar", JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        switch(modif){
            case "Nombre del producto":
                String newName = JOptionPane.showInputDialog("Inserte el nuevo nombre del producto");
                obj.setNombre(newName);
                break;
            case "Cantidad":
                int newCantidad = Integer.parseInt(JOptionPane.showInputDialog("Inserte la nueva cantidad de unidades del producto"));
                obj.setCantidad(newCantidad);
                break;
            case "Precio Venta":
                int newPrecioVenta = Integer.parseInt(JOptionPane.showInputDialog("Inserte el nuevo precio de venta del producto"));
                obj.setPrecio_venta(newPrecioVenta);
                break;
            case "Precio Distribuidor":
                int newPrecioDistribuidor = Integer.parseInt(JOptionPane.showInputDialog("Inserte el nuevo precio de venta del producto"));
                obj.setPrecio_distribuidor(newPrecioDistribuidor);
                break;
        }
        actualizaTabla();
    }                                      

    private void FacturaciónMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        Facturacion ventFac = new Facturacion(inventario,Facturacion);
        Principal.ShowPanel(ventFac);
    }                                        

    private void PedidosMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        Pedidos ventPed = new Pedidos(inventario,Facturacion);
        Principal.ShowPanel(ventPed);
    }                                    

    private void FinanzasMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        Finanzas ventFin = new Finanzas(inventario,Facturacion);
        Principal.ShowPanel(ventFin);
    }                                     

    private void BarrGuardarMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        sz.WriteObjectToFile(inventario);
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Archivo;
    private javax.swing.JLabel Ayuda;
    private javax.swing.JLabel BarrAñadir;
    private javax.swing.JLabel BarrBuscar;
    private javax.swing.JLabel BarrCambId;
    private javax.swing.JLabel BarrEliminar;
    private javax.swing.JLabel BarrGuardar;
    private javax.swing.JLabel Buscar;
    private javax.swing.JLabel Consultas;
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel Edicion;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Facturación;
    private javax.swing.JLabel Finanzas;
    private javax.swing.JLabel InventarioOpc;
    private javax.swing.JLabel Modificar;
    private javax.swing.JLabel Nuevo;
    private javax.swing.JPanel PanelCalculadora;
    private javax.swing.JLabel Pedidos;
    private javax.swing.JLabel Reportes;
    private javax.swing.JLabel Ventana;
    private javax.swing.JLabel Vista;
    private javax.swing.JPanel barraGrisSup;
    private javax.swing.JLabel barraInventario;
    public javax.swing.JTable inventarioTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textoBusqueda;
    // End of variables declaration                   
}
