/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author espin
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Splash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBackground = new javax.swing.JPanel();
        LoadingBar = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        LoadingValue = new javax.swing.JLabel();
        LoadingText = new javax.swing.JLabel();
        Splash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelBackground.setBackground(new java.awt.Color(255, 255, 255));
        PanelBackground.setPreferredSize(new java.awt.Dimension(500, 745));
        PanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingBar.setBackground(new java.awt.Color(102, 204, 255));
        PanelBackground.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 694, 480, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        LoadingValue.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LoadingValue.setText("0%");

        LoadingText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        LoadingText.setText("Loading . . .");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LoadingText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                .addComponent(LoadingValue)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoadingValue)
                    .addComponent(LoadingText))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        PanelBackground.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 500, 60));

        Splash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/splash.jpg"))); // NOI18N
        PanelBackground.add(Splash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Splash sp = new Splash();
        sp.setVisible(true);
        
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep(100);
                sp.LoadingValue.setText(i+"%");
                
                if(i==10){
                    sp.LoadingText.setText("Organizando cajas ...");
                }
                if(i==20){
                    sp.LoadingText.setText("Checkeando articulos ...");
                }
                if(i==50){
                    sp.LoadingText.setText("Calculando impuestos ...");
                }
                if(i==60){
                    sp.LoadingText.setText("Conectando a base de datos ...");
                }
                if(i==70){
                    sp.LoadingText.setText("Conexion realizada ...");
                }
                if(i==80){
                    sp.LoadingText.setText("Ejecutando aplicación ...");
                }
                sp.LoadingBar.setValue(i);
            }
            Principal principal=new Principal();
            Cuenta cuenta=new Cuenta();
            sp.dispose();
            principal.setVisible(true);
            cuenta.setVisible(true);
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);  
        }  
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingText;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JPanel PanelBackground;
    private javax.swing.JLabel Splash;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
